## Import Packages

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as opt
import math

## Load Data and add Time Column

In [6]:
# creates pandas dataframe from csv file with data
myData = pd.read_csv("Data/Wrist190Hz.csv")

# defines frequency of operation
f = 90 #Hz

# creates empty list
timeArray = []

# determines number of data points
N = len(myData)

# adds i divided by by frequency to list
for i in range(1,N+1): 
    timeArray.append(i*(1/f))

# assigns list as new column to pandas dataframe
myData['Calculated Time(s)'] = timeArray

# prints the pandas dataframe with the new column added
myData

,Accelerometer X,Accelerometer Y,Accelerometer Z,Time(s),Calculated Time(s)
0,-0.133,0.469,-0.922,0.011,0.011111
1,-0.141,0.445,-0.910,0.022,0.022222
2,-0.133,0.441,-0.914,0.033,0.033333
3,-0.137,0.438,-0.914,0.044,0.044444
4,-0.137,0.441,-0.906,0.055,0.055556
...,...,...,...,...,...
10795,-0.340,0.563,-0.793,118.756,119.955556
10796,-0.340,0.563,-0.789,118.767,119.966667
10797,-0.340,0.563,-0.793,118.778,119.977778
10798,-0.340,0.559,-0.793,118.789,119.988889
10799,-0.348,0.551,-0.793,118.800,120.000000

## Euclidean Norm minus-One

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6874221/

In [7]:
# creates empty list
raw = []

# calculates euclidean norm of acceleration components
euclidean_norm = np.sqrt((myData["Accelerometer X"])**2  +  (myData["Accelerometer Y"])**2  + (myData["Accelerometer Z"])**2)

# subtracts 1 from eucliean norms
raw = euclidean_norm - 1

# assigns list as new column to pandas dataframe
myData['Raw'] = raw

# prints the pandas dataframe with the new column added
myData

,Accelerometer X,Accelerometer Y,Accelerometer Z,Time(s),Calculated Time(s),Raw
0,-0.133,0.469,-0.922,0.011,0.011111,0.042945
1,-0.141,0.445,-0.910,0.022,0.022222,0.022744
2,-0.133,0.441,-0.914,0.033,0.033333,0.023507
3,-0.137,0.438,-0.914,0.044,0.044444,0.022746
4,-0.137,0.441,-0.906,0.055,0.055556,0.016900
...,...,...,...,...,...,...
10795,-0.340,0.563,-0.793,118.756,119.955556,0.030251
10796,-0.340,0.563,-0.789,118.767,119.966667,0.027176
10797,-0.340,0.563,-0.793,118.778,119.977778,0.030251
10798,-0.340,0.559,-0.793,118.789,119.988889,0.028071
10799,-0.348,0.551,-0.793,118.800,120.000000,0.026428

## Vector Magnitude Count(VMC) aka Mean Amplitude Deviation
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4527117/

In [8]:
# **calculates for FIRST epoch only**

# sets epoch length
epoch_length = 5 #seconds

# calulates number of samples and sum of values in first epoch
n = 0
epoch_sum = 0
while myData["Time(s)"][n] < epoch_length:
    epoch_sum += myData["Raw"][n]
    n += 1

# prints n for troubleshooting
print("Num samples in epoch:", n)

# calculates mean resultant value
mean_resultant_value = epoch_sum / n

# calculates cumulative sum
cumulative_sum = 0
for i in range(epoch_length):
    cumulative_sum += abs(myData["Raw"][i] - mean_resultant_value)

# calculates MAD of first epoch and prints for troubleshooting
MAD = 1/n * cumulative_sum
print("MAD of first epoch:", MAD)

Num samples in epoch: 454
MAD of first epoch: 0.00010001440834434512

## Unnormalized Activity Index

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6874221/

## Peak Finder Algorithm